image: "gpdowning/python"

before_script:
  - apt-get update -yq && apt-get upgrade -yq && apt-get install -yq curl git nano
  - curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - apt-get install -yq nodejs build-essential
  - npm install -g npm
  - npm install newman --global
  - python --version
  - node --version
  - npm --version
  - newman --version


test:
  script:
    - cd backend
    - ls
    - newman run Postman.json