test:
  image: gpdowning/python
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - ls
  - cd Front-End
  - pip install -r requirements.txt
  - npm install newman --global
  - newman run ../Postman.json