version: '3'

services:
        front-end:
                build: .
                volumes:
                        - .:/home/website
                ports:
                        - "5000:5000"
                command:
                        python -u app.py
        back-end:
                build: .
                volumes:
                        - .:/home/website
                ports:
                        - "5001:5000"
                command:
                        python -u app.py
