version: '3'

services:
        back-end:
                build: .
                volumes:
                        - .:/home/website
                ports:
                        - "80:5000"
                command:
                        python -u app.py
